### ISSUE TITLE
cannot login opensea

### ISSUE THREAD

**Issue by Ugijago** [maximedrn/opensea_automatic_uploader#53]
weirdly just recently cannot login to opensea, its just opening metamask download link when bot and i try click metamask wallet in opensea login page.

**Comment by mpi42** [comment]
same problem

**Comment by maximedrn** [comment]
Hello, this error is from OpenSea. You can try on any browser that has the MetaMask extension and it doesn't work.
I will let you know if the error is fixed.

**Comment by maximedrn** [comment]
Fixed it! I added a click on the "Show more options" button, it updates the Opensea backend and changes the URL of the MetaMask button from the MetaMask download URL to the extension URL.

**Comment by Ugijago** [comment]
weird bot nowt click metamask pop up

**Comment by maximedrn** [comment]
It's still buggy, I'm working on it

**Comment by mpi42** [comment]
it is now hanging on the sign message as i can see

**Comment by Ugijago** [comment]
still cannot login bot just chilling when pop up show 🤔, well for now i want to sleep i will wait for fix thanks 👍

**Comment by gch4n69** [comment]
Yes. same problem here. Cannot login to opensea.

**Comment by Ugijago** [comment]
the cause bot chilling because i update metamask crx to  newest version , why newest version make bot just chilling when metamask pop up show up? now i can upload again use old metamsk crx

**Comment by mpi42** [comment]
how i can i use the old metamask crx?

**Comment by Ugijago** [comment]
just download from this github

**Comment by gch4n69** [comment]
> 

In the last repository? Just show the file thr older metamask. Thanks

**Comment by gch4n69** [comment]
What version of metamask?

**Comment by Ugijago** [comment]
many times bot eror to login maybe consider make sleep command between action when login to opensea ? maybe can minimizing eror login and eror uploading and listing nft

**Comment by gch4n69** [comment]
> I made something that seems to work now.

Cannot login opensea. what version of metamask are you using?

**Comment by PollitoMalo** [comment]
it works for me, with the latest version of metamask and the same version of chromedriver and chrome.

**Comment by hiren195** [comment]
Not working for me, it is hanging on the "Sign" button click in metamask window

**Comment by maximedrn** [comment]
> > I made something that seems to work now.
> 
> Cannot login opensea. what version of metamask are you using?

Use the CRX file from the `assets/` folder.

**Comment by maximedrn** [comment]
> Not working for me, it is hanging on the "Sign" button click in metamask window

Update to the newest version of the bot. It should work.

**Comment by maximedrn** [comment]
> the cause bot chilling because i update metamask crx to newest version , why newest version make bot just chilling when metamask pop up show up? now i can upload again use old metamsk crx. thx for fix 👍

I advise not to update the extension. The current version still works and was not responsible for the connection problems. Opensea had some problems yesterday that prevented the bot from working properly at certain times.

**Comment by gch4n69** [comment]
> Use the CRX file from the `assets/` folder.

I'm using metamask int he assets/folder. Why stuck in "Signature Request", reload login.

**Comment by hiren195** [comment]
> > Not working for me, it is hanging on the "Sign" button click in metamask window
> 
> Update to the newest version of the bot. It should work.

Checked again using new version of bot and it is being stuck on "Signature Request" metamask screen

**Comment by mrrehman** [comment]
@maximedrn it still didn't work. stuck to opensea login...any solution?

**Comment by Ugijago** [comment]
can you make history log for failed upload or sale? many mysterious turn off power in my place, i cant trace back what happen before turn off i dont know which number is failed in upload and sale

**Comment by maximedrn** [comment]
Hi! I have released a new version, I need feedback as I am fixing this problem blindly as I do not encounter any errors during the connection.

**Comment by hiren195** [comment]
> Hi! I have released a new version, I need feedback as I am fixing this problem blindly as I do not encounter any errors during the connection.

It is working for me.. thanks

**Comment by gch4n69** [comment]
Yes it's working. Thank you @maximedrn

**Comment by maximedrn** [comment]
> can you make history log for failed upload or sale? many mysterious turn off power in my place, i cant trace back what happen before turn off i dont know which number is failed in upload and sale

Errors were not printed, I just add the print of them when an exception occured. I'll add a log file that refer which NFT failed to upload/sell.

**Comment by ahmetburak** [comment]
I think the problem of not being able to login to Opensea is caused by a cloudflare protection from Opensea. At least that's the case for me, I get a screen like this.
<img width="1100" alt="Screen Shot 2023-07-02 at 10 05 53" src="https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale/assets/36148264/7646ad9b-e977-41bd-8d5d-c7b056091210">
